using System.Collections.Immutable;

internal record TypeModel
{
    public ImmutableArray<string> PragmaDisables { get; }
    public ImmutableArray<string> PreDeclarationElements { get; }
    public string Namespace { get; }
    public ImmutableArray<string> Keywords { get; }
    public string Kind { get; }
    public string Name { get; }
    public string Implements { get; }
    public BaseTypeElementModel[] Elements { get; }

    public TypeModel(
        string[] pragmaDisables,
        string[] preDeclarationElements,
        string @namespace, 
        string[] keywords, 
        string kind,
        string name, 
        string implements,
        BaseTypeElementModel[] elements)
    {
        PragmaDisables = ImmutableArray.Create(pragmaDisables);
        PreDeclarationElements = ImmutableArray.Create(preDeclarationElements);
        Namespace = @namespace;
        Keywords = ImmutableArray.Create(keywords);
        Kind = kind;
        Name = name;
        Implements = implements;
        Elements = elements;
    }

    public void Build(CodeWriter codeWriter)
    {
        codeWriter.WriteLine("// <auto-generated />");
        foreach (var pragmaDisable in PragmaDisables)
        {
            codeWriter.WriteLine($"#pragma warning disable {pragmaDisable}");
        }
        foreach (var preDeclarationElement in PreDeclarationElements)
        {
            codeWriter.WriteLine(preDeclarationElement);
        }
        if (PreDeclarationElements.Length > 0)
        {
            codeWriter.WriteLine();
        }
        codeWriter.StartNamespace(Namespace);
        foreach (var keyword in Keywords)
        {
            codeWriter.Write($"{keyword} ");
        }

        var typeDeclaration = string.IsNullOrEmpty(Implements) ? $"{Kind} {Name}" : $"{Kind} {Name} : {Implements}";
        if (Elements.Length > 0)
        {
            using (codeWriter.CreateScope(typeDeclaration))
            {
                foreach (var element in Elements)
                {
                    element.Build(codeWriter);
                }
            }
        }
        else
        {
            codeWriter.WriteLine($$"""{{typeDeclaration}} { }""");
        }
        
        codeWriter.EndNamespace(Namespace);
        foreach (var pragmaDisable in PragmaDisables)
        {
            codeWriter.WriteLine($"#pragma warning restore {pragmaDisable}");
        }
    }
}